trigger:
  branches:
    include:
      - dev
      - DEV
  paths:
    include:
      - force-app/*

# pull request trigger
pr: none

variables:
- group: dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: SFDeployAndValidate
    jobs:
      - job: SFDeployAndValidate
      - template: ../ado_templates/template.yml
        parameters:
            SF_USER_NAME: $(SF_USER_NAME)
            SF_ALIAS: $(SF_ALIAS)
            SF_CLIENT_ID: $(SF_CLIENT_ID)
            SF_INSTANCE_URL: $(SF_INSTANCE_URL)
            SECURE_FILE_NAME: 'server-dev.key'
            PR_MERGED: true
            BY_PASS_CODE_COVERAGE: $(BY_PASS_CODE_COVERAGE)
            BY_PASS_CODE_ANALYZER: $(BY_PASS_CODE_ANALYZER)
      