# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: SFBuild
    jobs:
      - job: SFBuild
        steps:
          - script: echo ""SFBuild is running"
            displayName: Single Line Script
          - script: |
              echo "Multiple Line 1"
              echo "Multiple Line 2"

  - stage: SFDeployAndValidate
    jobs:
      - job: SFValidate
        steps:
          - script: npm install -g @salesforce/cli
            displayName: Install Salesforce CLI
          - script: sf --version
            displayName: Verify SF-CLI Installation
          - script: |
              echo 'y' | sf plugins install sfdx-git-delta
              sf plugins install @salesforce/sfdx-scanner
            displayName: Install Required Plugins
      - job: SFDeploy
        steps:
          - script: echo ""SFBuild is running"
            displayName: Single Line Script
          - script: |
              echo "Multiple Line 1"
              echo "Multiple Line 2" 
  - stage: SFTest
    jobs:
      - job: SFBuild
        steps:
          - script: echo ""SFBuild is running"
            displayName: Single Line Script
          - script: |
              echo "Multiple Line 1"
              echo "Multiple Line 2"
