# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: SFBuild
    jobs:
      - job: SFBuild
        steps:
          - script: echo ""SFBuild is running"
            displayName: Single Line Script
          - script: |
              echo "Multiple Line 1"
              echo "Multiple Line 2"

  - stage: SFDeploy
    jobs:
      - job: SFBuild
        steps:
          - script: echo ""SFBuild is running"
            displayName: Single Line Script
          - script: |
              echo "Multiple Line 1"
              echo "Multiple Line 2" 

  - stage: SFTest
    jobs:
      - job: SFBuild
        steps:
          - script: echo ""SFBuild is running"
            displayName: Single Line Script
          - script: |
              echo "Multiple Line 1"
              echo "Multiple Line 2"
